version: "3.8"

services:
  # ✅ DATABASE
  postgres:
    image: postgres:16
    container_name: aquasmart-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADYLLSXNPOSTGRES
      POSTGRES_DB: db_aquasmart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - aquasmart-network

  # ✅ SERVER
  aquasmart-server:
    container_name: aquasmart-server
    build:
      context: ../..
      dockerfile: src/apps/Aquasmart.Server/Dockerfile
    image: aquasmart/server:latest
    ports:
      - "5047:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - aquasmart-network

  # ✅ WEB
  aquasmart-web:
    container_name: aquasmart-web
    build:
      context: ../..
      dockerfile: src/apps/Aquasmart.Web/Dockerfile
    image: aquasmart/web:latest
    ports:
      - "5048:80"
    depends_on:
      - aquasmart-server
    restart: unless-stopped
    networks:
      - aquasmart-network

volumes:
  postgres_data:

networks:
  aquasmart-network:
    driver: bridge