services:
  aquasmart-server:
    container_name: aquasmart-server
    build:
      context: ../..
      dockerfile: src/apps/Aquasmart.Server/Dockerfile
    image: aquasmart/server:latest
    ports:
      - "5047:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - aquasmart-network

  aquasmart-web:
    container_name: aquasmart-web
    build:
      context: ../..
      dockerfile: src/apps/Aquasmart.Web/Dockerfile
    image: aquasmart/web:latest
    ports:
      - "5048:80"
    depends_on:
      - aquasmart-server
    restart: unless-stopped
    networks:
      - aquasmart-network

networks:
  aquasmart-network:
    driver: bridge
